### ISSUE TITLE
error while creating oci_identity_user.nc-bucket-user

### ISSUE THREAD

**Issue by krimac** [chadgeary/cloudoffice#13]
hi, thanks for all your work, I'm stuck on deploying : 

oci_identity_user.nc-bucket-user: Creating...
╷
`│ Error: 400-IdcsConversionError, Post request failed{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error","urn:ietf:params:scim:api:oracle:idcs:extension:messages:Error"],"detail":"The primary email must be specified.","status":"400","urn:ietf:params:scim:api:oracle:idcs:extension:messages:Error":{"messageId":"error.identity.user.primaryEmailNotSpecified"}}
`

**Comment by chadgeary** [comment]
That's an interesting error - it looks like the oracle (oci) provider documentation is out of date and the requirements for this resource have changed.

https://github.com/oracle/terraform-provider-oci/issues/1622

I believe I can set this to an aliased email address based on the caller's (your) email address, testing it now.

**Comment by chadgeary** [comment]
commit 3db73de adds a placeholder email address, please update your repository with `git pull`. If you've already customized oci.tfvars then move oci.tfvars to a different file, git pull, then move it back like this:
```bash
mv oci.tfvars custom.tfvars
git pull
mv custom.tfvars oci.tfvars
```
