### ISSUE TITLE
The conditional check 'swap_file.stat.exists|bool == false' failed.

### ISSUE THREAD

**Issue by TechWizardDD** [chadgeary/cloudoffice#15]
While i try to deploy ,  getting following error :
" fatal: [localhost]: FAILED! => {"msg": "The conditional check 'swap_file.stat.exists|bool == false' failed. The error was: No filter named 'bool' found.\n\nThe error appears to be in '/home/user/cloudoffice/playbooks/cloudoffice_ubuntu.yml': line 32, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: create swap file if not exists\n      ^ here\n"} " . 
I suspect that it is connected with changes no-tests-as-filters in ansible "Prior to Ansible 2.5, Jinja2 tests included within Ansible were most often used as filters. The large difference in use is that filters are referenced as variable | filter_name while Jinja2 tests are referenced as variable is test_name."  , but dont know how to fix this issue.

**Comment by chadgeary** [comment]
Hey, this should be fixed in https://github.com/chadgeary/cloudoffice/pull/16

cheers!
