### ISSUE TITLE
Why is upstream protocol `http` and not `https` for `/nc`?

### ISSUE THREAD

**Issue by JCZuurmond** [chadgeary/cloudoffice#2]
For the nextcloud endpoint the upstream protocol is [`http`](https://github.com/chadgeary/cloudoffice/blob/aae52bf0fecef008c766a8cb111c638b4a220dd9/playbooks/nginx/proxy-confs/cloudoffice.conf#L16), while or the root location (onlyoffice) it is [`https`](https://github.com/chadgeary/cloudoffice/blob/aae52bf0fecef008c766a8cb111c638b4a220dd9/playbooks/nginx/proxy-confs/cloudoffice.conf#L31). Why the difference? Should they not both be `https`? Or does it not matter?

**Comment by chadgeary** [comment]
We use the Apache (no duckdns) or Nginx (with duckdns) proxy containers for HTTPS to Nextcloud. Nextcloud HTTP is never exposed.
