### ISSUE TITLE
Warning `"Strict-Transport-Security" HTTP header is not set`

### ISSUE THREAD

**Issue by JCZuurmond** [chadgeary/cloudoffice#4]
In the adminstartion overview I see the following warning `The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips ↗.`. It links to this [doc page](https://docs.nextcloud.com/server/22/admin_manual/installation/harden_server.html). How do we set the "Strict-Transport-Security" HTTP header?

**Comment by chadgeary** [comment]
It can be done via the nginx container (web proxy) for duckdns - see the nginx confirms under playbooks/
