### ISSUE TITLE
Using the nginx config from the Nextcloud documentation

### ISSUE THREAD

**Issue by JCZuurmond** [chadgeary/cloudoffice#8]
The Nextcloud documentation has a [nginx config](https://docs.nextcloud.com/server/22/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-the-nginx-webroot). Should we use that?

It for example contains `http2` which is part of the [server tuning page](https://docs.nextcloud.com/server/22/admin_manual/installation/server_tuning.html#enable-http-2-for-faster-loading).

```
    listen 443      ssl http2;
    listen [::]:443 ssl http2;
```

I am not familiar with nginx and its configuration, but I trust the Nextcloud settings.

**Comment by chadgeary** [comment]
@JCZuurmond this looks good - added 8ffd774

**Comment by JCZuurmond** [comment]
Cool, and what about all the settings?
